In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4]

In [5]:
a=np.array(lst)

In [6]:
a

array([1, 2, 3, 4])

In [7]:
a.shape

(4,)

In [10]:
nested_list=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
b=np.array(nested_list)

In [11]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
b.shape


(4, 3)

In [15]:
b.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [16]:
b.size

12

In [17]:
b.reshape(1,2,6)

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]])

In [18]:
a.reshape(1,4)

array([[1, 2, 3, 4]])

In [20]:
np.array(['sri_narahari',1,2,3,4])

array(['sri_narahari', '1', '2', '3', '4'], dtype='<U12')

In [23]:
np.array([1,2,3],ndmin=5)

array([[[[[1, 2, 3]]]]])

In [24]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
b[2][2]

9

In [28]:
b[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [38]:
b[[0,3]]

array([[ 1,  2,  3],
       [10, 11, 12]])

In [41]:
b[[0,3],[0,2]]

array([ 1, 12])

In [42]:
np.matrix([1,2,3,4])

matrix([[1, 2, 3, 4]])

In [43]:
np.array(np.matrix([1,2,3,4]))

array([[1, 2, 3, 4]])

In [46]:
issubclass(np.matrix,np.ndarray)

True

In [47]:
arr1=np.array([1,2,3,4])

In [48]:
arr1


array([1, 2, 3, 4])

In [49]:
arr2=np.asarray([1,2,3,4])

In [50]:
arr2

array([1, 2, 3, 4])

In [51]:
arr1 is arr2

False

In [52]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])