In [48]:
#is vs ==
#np.array
#np.asarray

In [49]:
lst1=['sri','sri1','sri2']


In [50]:
lst2=['sri','sri1','sri2']

In [51]:
#checks whther elements are same
lst1==lst2

True

In [52]:
lst1 is lst2

# is refers to same objetc in memory

False

In [53]:
##shallow copy vs deep copy

In [54]:
##shallow copy # a will change
import numpy as np
a=np.array([1,2,3,4])

In [55]:
a
b=a

In [56]:
a[0]=5

In [57]:
a

array([5, 2, 3, 4])

In [58]:
b

array([5, 2, 3, 4])

In [59]:
####deep copy ## a wont change
a=np.array([1,2,3,4])
b=a.copy()

In [60]:
b[0]=7

In [61]:
b

array([7, 2, 3, 4])

In [62]:
a

array([1, 2, 3, 4])

In [63]:
#np.array
#np.asarray

In [64]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [65]:
b=np.asarray([1,2,3,4])
b

array([1, 2, 3, 4])

In [66]:
b is a

False

In [67]:
np.asarray(a) is a ##same locatiom

True

In [68]:
np.array(a) is a ## diff location

False

In [69]:
type(np.array([1,2,3,4]))

numpy.ndarray

In [70]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)

In [71]:
mat.ndim

2

In [73]:
mat.shape

(3, 3)

In [74]:
mat.size

9

In [75]:
mat.dtype

dtype('int32')

In [78]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [79]:
np.arange(1,12,3)

array([ 1,  4,  7, 10])

In [80]:
np.arange(1,12,2.5)

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [83]:
np.arange(1,12,2).reshape(3,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [84]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [88]:
np.linspace(0,10,50).shape

(50,)

In [89]:
np.linspace(0,10,50).reshape(2,25)

array([[ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
         2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
         3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
         4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918],
       [ 5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
         6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
         7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
         8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
         9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]])

#Matrix Creation

In [94]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [95]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [96]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [99]:
x=np.arange(16).reshape(4,4)

In [100]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [102]:
x.diagonal()

array([ 0,  5, 10, 15])

In [103]:
np.diag(x)

array([ 0,  5, 10, 15])

In [104]:
np.diag(x,k=1)

array([ 1,  6, 11])

In [105]:
np.diag(x,k=2)

array([2, 7])

In [107]:
np.diag(x,k=3)

array([3])

In [108]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [109]:
np.random.rand(3)

array([0.83208038, 0.25884431, 0.55770923])

In [114]:
np.random.rand(3,4)

array([[0.85702617, 0.36590912, 0.97419947, 0.14418288],
       [0.88709922, 0.35596138, 0.69622689, 0.353314  ],
       [0.10890629, 0.69625406, 0.63048085, 0.5067598 ]])

In [117]:
np.random.randn(3,4)

array([[ 0.72308448,  0.01745023, -1.2992389 , -0.72493376],
       [ 1.4598373 , -0.75425379, -0.15116565,  1.85142572],
       [ 0.57676406, -0.34852427, -1.44731035, -0.39632412]])

In [190]:
a=np.random.randint(1,1000,30)

In [191]:
a

array([ 63,  34, 476,  68, 204, 589,  74, 355,  62, 858, 691, 823, 934,
       691, 334, 367, 569, 934, 898, 704, 686, 714,   6, 982, 573, 648,
       911, 901, 381, 772])

In [193]:
np.sort(a)

array([  6,  34,  62,  63,  68,  74, 204, 334, 355, 367, 381, 476, 569,
       573, 589, 648, 686, 691, 691, 704, 714, 772, 823, 858, 898, 901,
       911, 934, 934, 982])

In [195]:
a.max()

982

In [196]:
a.min()

6

In [197]:
a

array([ 63,  34, 476,  68, 204, 589,  74, 355,  62, 858, 691, 823, 934,
       691, 334, 367, 569, 934, 898, 704, 686, 714,   6, 982, 573, 648,
       911, 901, 381, 772])

In [198]:
a.argmax()

23

In [199]:
a.shape

(30,)

In [200]:
a=np.random.randint(0,100,30).reshape(5,6)
a

array([[71,  4, 95, 64, 97, 88],
       [13,  9, 55, 21,  8, 25],
       [ 7, 23, 88, 30, 82, 60],
       [26, 64, 34, 60, 70, 83],
       [21, 67,  7,  0, 77, 45]])

In [201]:
a

array([[71,  4, 95, 64, 97, 88],
       [13,  9, 55, 21,  8, 25],
       [ 7, 23, 88, 30, 82, 60],
       [26, 64, 34, 60, 70, 83],
       [21, 67,  7,  0, 77, 45]])

In [202]:
a*2

array([[142,   8, 190, 128, 194, 176],
       [ 26,  18, 110,  42,  16,  50],
       [ 14,  46, 176,  60, 164, 120],
       [ 52, 128,  68, 120, 140, 166],
       [ 42, 134,  14,   0, 154,  90]])

In [204]:
b=np.random.randint(0,100,30).reshape(5,6)
b

array([[88,  4, 67,  9, 16,  4],
       [37, 30, 65, 38, 66, 24],
       [57, 79, 94, 32, 27, 19],
       [62, 88, 59, 90,  3,  7],
       [35, 99, 88, 59, 54, 65]])

In [205]:
a+b

array([[159,   8, 162,  73, 113,  92],
       [ 50,  39, 120,  59,  74,  49],
       [ 64, 102, 182,  62, 109,  79],
       [ 88, 152,  93, 150,  73,  90],
       [ 56, 166,  95,  59, 131, 110]])

In [207]:
b=np.random.randint(0,100,30).reshape(3,3)
b

ValueError: cannot reshape array of size 30 into shape (3,3)

In [208]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


NameError: name 'ri' is not defined

In [209]:
a/0

C:\Users\SNARAHA1\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\SNARAHA1\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, nan, inf, inf]])

In [210]:
a=np.random.randint(0,100,30)

In [211]:
a

array([ 3, 48, 88, 89, 52, 77, 68, 66, 21, 39, 35, 33, 97, 77, 94, 79, 65,
       69, 15, 57, 27, 98, 25, 93, 40, 34, 10, 45, 39, 45])

In [212]:
a[3]

89

In [215]:
a[3:15]=100

In [216]:
a

array([  3,  48,  88, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [217]:
a=np.random.randint(0,100,30)

In [218]:
a

array([29, 46, 70, 65, 43, 43, 51, 57, 24,  5, 75, 86,  4, 30, 47, 92, 41,
       70, 58, 88, 92, 10, 69, 69, 44, 18, 38, 52,  6, 92])

In [219]:
a[a>25]

array([29, 46, 70, 65, 43, 43, 51, 57, 75, 86, 30, 47, 92, 41, 70, 58, 88,
       92, 69, 69, 44, 38, 52, 92])